#Requires -Version 5.1
<#
.SYNOPSIS
  Shared version helpers for Batch ST-Link Flasher build/install scripts.
#>

$script:VersionFile = Join-Path (Split-Path -Parent $PSScriptRoot) "packaging\version.json"

function Get-VersionFilePath {
    return $script:VersionFile
}

function Read-ProjectVersion {
    $path = Get-VersionFilePath
    if (-not (Test-Path $path)) {
        throw "Missing version file: $path"
    }
    $json = Get-Content -LiteralPath $path -Raw -Encoding UTF8 | ConvertFrom-Json
    $major = [int]$json.major
    $minor = [int]$json.minor
    $patch = [int]$json.patch
    $build = [int]$json.build
    return [pscustomobject]@{
        Major       = $major
        Minor       = $minor
        Patch       = $patch
        Build       = $build
        Version     = "{0}.{1}.{2}.{3}" -f $major, $minor, $patch, $build
        BaseVersion = "{0}.{1}.{2}" -f $major, $minor, $patch
    }
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    $encoding = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Write-ProjectVersion {
    param(
        [Parameter(Mandatory = $true)][int]$Major,
        [Parameter(Mandatory = $true)][int]$Minor,
        [Parameter(Mandatory = $true)][int]$Patch,
        [Parameter(Mandatory = $true)][int]$Build
    )
    $path = Get-VersionFilePath
    $payload = [ordered]@{
        major = $Major
        minor = $Minor
        patch = $Patch
        build = $Build
    }
    Write-Utf8NoBom -Path $path -Content (($payload | ConvertTo-Json) + "`n")
}

function Sync-VersionArtifacts {
    param(
        [Parameter(Mandatory = $true)]$Info
    )
    $root = Split-Path -Parent $PSScriptRoot
    $version = $Info.Version

    # Python runtime module
    $versionPy = Join-Path $root "src\batch_stlink_flasher\_version.py"
    $pyBody = @"
# Auto-generated by scripts/bump_version.ps1 / build scripts. Do not edit by hand.
__version__ = "$version"
__version_info__ = ($($Info.Major), $($Info.Minor), $($Info.Patch), $($Info.Build))
"@
    Write-Utf8NoBom -Path $versionPy -Content ($pyBody.TrimEnd() + "`n")

    # pyproject.toml
    $pyproject = Join-Path $root "pyproject.toml"
    $toml = Get-Content -LiteralPath $pyproject -Raw -Encoding UTF8
    $toml2 = [regex]::Replace($toml, '(?m)^version\s*=\s*"[^"]+"', "version = `"$version`"")
    Write-Utf8NoBom -Path $pyproject -Content $toml2

    # Inno Setup
    $iss = Join-Path $root "packaging\installer.iss"
    if (Test-Path $iss) {
        $issText = Get-Content -LiteralPath $iss -Raw -Encoding UTF8
        $issText2 = [regex]::Replace(
            $issText,
            '(?m)^#define MyAppVersion "[^"]+"',
            "#define MyAppVersion `"$version`""
        )
        Write-Utf8NoBom -Path $iss -Content $issText2
    }
}
